steps:
  # Prebuild the YARN package
  - command: "cd App && yarn install && yarn build"
    label: ":ubuntu: :nodejs: :hammer_and_wrench:"
    artifact_paths:
      - "App/node_modules/**/*"
    agents:
      geo: "co"
      arch: "amd64"

  - wait

  - command: "./.buildkite/build.sh"
    label: ":ubuntu: :docker: :hammer_and_wrench:"
    agents:
      geo: "co"
      arch: "amd64"

  - command: "./.buildkite/build.sh"
    label: ":raspberry-pi: :docker: :hammer_and_wrench:"
    agents:
      geo: "co"
      arch: "arm64v8"

  - block: "Release?"

  - command: "./.buildkite/push.sh"
    label: ":docker: ${PRODUCT_NAME}:${DOCKER_BUILD_TAG} :rocket:"
    agents:
      geo: "co"
      arch: "amd64"
