steps:
  # Linux x64 Stand-Alone
  - label: ":ubuntu: AMD :hammer_and_wrench: x64"
    command: "./.buildkite/maker.sh electron build WebApp"
    agents:
      geo: "co"
      arch: "amd"
      os: "linux"
      cpu: "64"
      arch_variant: "x64"

  # OSX x64 Stand-Alone can be built on linux
  - label: ":mac: AMD :hammer_and_wrench: x64"
    command: "./.buildkite/maker.sh electron build WebApp"
    agents:
      geo: "co"
#      arch: "amd"
      os: "mac"
#      cpu: "64"
#      arch_variant: "x64"

  # Windows has dependencies installed natively, and needs a native style invocation.
  - label: ":windows: AMD :hammer_and_wrench: x64"
    command: ".buildkite\\maker.cmd electron build WebApp"
    agents:
      geo: "co"
      arch: "amd"
      os: "win"
      cpu: "64"
      arch_variant: "x64"

  # AMD64 Docker Container
  - label: ":ubuntu: AMD :hammer_and_wrench: x64 :docker:"
    command: "./.buildkite/maker.sh container build makerverse/core"
    agents:
      geo: "co"
      arch: "amd"
      os: "linux"
      cpu: "64"

  # ARM32v7 Docker Container
  - label: ":raspberry-pi: ARM :hammer_and_wrench: v7 :docker:"
    command: "./.buildkite/maker.sh container build makerverse/core"
    agents:
      geo: "co"
      hw: "rpi"
      # arch: "arm"
      # cpu: "32"
      # arch_variant: "v7"

  # ARM64v8 Docker Container
  - label: ":raspberry-pi: ARM :hammer_and_wrench: v8 :docker:"
    command: "./.buildkite/maker.sh container build makerverse/core"
    agents:
      geo: "co"
      hw: "rpi"
      # arch: "arm"
      # cpu: "32"
      # arch_variant: "v7"

  # Block release
  - block: "Release?"

  - label: ":docker: ${PRODUCT_NAME}:${DOCKER_BUILD_TAG} :rocket:"
    command: "./.buildkite/maker.sh container deploy makerverse/core"
    agents:
      geo: "co"
      arch: "amd"
      cpu: "64"
      os: "linux"

