steps:
  # Linux x64 Stand-Alone
  - command: "bash .buildkite/build-electron.sh"
    label: ".deb :ubuntu: AMD :hammer_and_wrench: x64"
    env:
      BUILD_ELECTRON: true
    artifact_paths:
      - "bin/Desktop/**/*"
    agents:
      geo: "co"
      arch: "amd"
      os: "linux"
      cpu: "64"
      arch_variant: "x64"

  # OSX x64 Stand-Alone can be built on linux
  - command: "bash .buildkite/build-electron.sh osx"
    label: ".app, .dmg :mac: AMD :hammer_and_wrench: x64"
    env:
      BUILD_ELECTRON: true
    artifact_paths:
      - "bin/Desktop/**/*"
    agents:
      geo: "co"
      arch: "amd"
      os: "mac"
      cpu: "64"
      arch_variant: "x64"

  # Windows has dependencies installed natively, and needs a native style invocation.
  - command: "cmd.exe /c \".buildkite\\build-electron.cmd\""
    label: ".exe :windows: AMD :hammer_and_wrench: x64"
    env:
      BUILD_ELECTRON: true
    artifact_paths:
      - "bin/Desktop/**/*"
    agents:
      geo: "co"
      arch: "amd"
      os: "win"
      cpu: "64"
      arch_variant: "x64"

  # AMD64 Docker Container
  - label: ":ubuntu: AMD :hammer_and_wrench: x64 :docker:"
    commands:
      - "npm install -g @openworkshop/maker-builder@latest"
      - "maker-container build makerverse/core"
    agents:
      geo: "co"
      arch: "amd"
      # cpu: "64"
      # arch_variant: "x64"

  # ARM32v7 Docker Container
  - label: ":raspberry-pi: ARM :hammer_and_wrench: v7 :docker:"
    commands:
    - "npm install -g @openworkshop/maker-builder@latest"
    - "maker-container build makerverse/core"
    agents:
      geo: "co"
      arch: "arm"
      # cpu: "32"
      # arch_variant: "v7"

  # ARM64v8 Docker Container
  - label: ":raspberry-pi: ARM :hammer_and_wrench: v8 :docker:"
    commands:
      - "npm install -g @openworkshop/maker-builder@latest"
      - "maker-container build makerverse/core"
    agents:
      geo: "co"
      arch: "arm"
      # cpu: "32"
      # arch_variant: "v7"

  # Block release
  - block: "Release?"

  - label: ":docker: ${PRODUCT_NAME}:${DOCKER_BUILD_TAG} :rocket:"
    commands:
      - "npm install -g @openworkshop/maker-builder@latest"
      - "maker-container build makerverse/core"
    agents:
      geo: "co"
      arch: "amd64"
