steps:
  # AMD64 Docker Container
  - command: "./.buildkite/build.sh"
    label: ":docker: :ubuntu: :hammer_and_wrench:"
    agents:
      geo: "co"
      arch: "amd64"

  # ARM Docker Container
  - command: "./.buildkite/build.sh"
    label: ":docker: :raspberry-pi: :hammer_and_wrench:"
    agents:
      geo: "co"
      arch: "arm64v8"

  # Block release
  - block: "Release?"

  - command: "./.buildkite/push.sh"
    label: ":docker: ${PRODUCT_NAME}:${DOCKER_BUILD_TAG} :rocket:"
    agents:
      geo: "co"
      arch: "amd64"
