#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn run lint-staged

if [[ $(which maker-project) ]]; then
  pushd $MH
  maker-project Makerverse prod
  popd
else
  echo "No maker-project found; skipped version checks."
fi
