#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn run lint-staged

if [ -d "$MH" ]; then
  pushd $MH
  node "./src/maker-builder/src/project.js" Makerverse prod
  popd
else
  echo "No \$MH directory found; skipped version checks."
fi
