#!/bin/bash

export LOCAL_DOMAIN="${LOCAL_DOMAIN:-oodalolly.camp}"
export PRODUCT_NAME="makerverse"

export NPM_LOCAL_REGISTRY="https://npm.${LOCAL_DOMAIN}"

export DOCKER_USER="inzania"
export DOCKER_REPO="$PRODUCT_NAME/core"
export DOCKER_LOCAL_REGISTRY="containers.${LOCAL_DOMAIN}"
export DOCKER_PUBLIC_REGISTRY="docker.io"

# Infer the real branch from CI env
if [ $BUILDKITE_PULL_REQUEST != "false" ]; then
  # Pull requests always build as the "beta" branch.
  export DOCKER_BUILD_TAG="beta"
elif [ $BUILDKITE_BRANCH != "master" ]; then
  # Non-master branch builds are always "alpha".
  export DOCKER_BUILD_TAG="alpha"
else
  # Full production build, tagged latest.
  export DOCKER_BUILD_TAG="latest"
fi
